#!/bin/sh

#  TRDB_processing.sh
#  
#
#  Created by Zook, Justin on 4/1/15.
#

#awk -v OFS="	" '{print $15,$2,$3,$4,$5,$6}' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.txt | sed 's/chr//;s/FastaHeader/#chr/' | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz

#/Applications/bioinfo/bedtools2/bin/mergeBed -i /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_all_merged.bed.gz

#awk '$6>94' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_all_gt95identity_merged.bed.gz

#awk '$4<7 && $6>94 && $3-$2>200' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_gt200bp_gt95identity_merged.bed.gz

#awk '$4<7 && $6>94 && $3-$2>50 && $3-$2<201' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_51to200bp_gt95identity_merged.bed.gz

#awk '$4<7 && $6>94 && $3-$2<51' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_lt51bp_gt95identity_merged.bed.gz


#awk '$4>6 && $6>94 && $3-$2>200' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_gt200bp_gt95identity_merged.bed.gz

#awk '$4>6 && $6>94 && $3-$2>50 && $3-$2<201' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_51to200bp_gt95identity_merged.bed.gz

#awk '$4>6 && $6>94 && $3-$2<51' /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_lt51bp_gt95identity_merged.bed.gz


#merge all repeats from TRDB and findSimpleRegions_quad.py in 3 size ranges: <51bp, 51-200, and | /Applications/bioinfo/tabix-0.2.6/bgzip >200bp
/Applications/bioinfo/bedtools2/bin/complementBed -i /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_lt51bp_gt95identity_merged.bed.gz -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_homopolymer_6to10.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_homopolymer_gt10.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_diTR_11to50.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_triTR_11to50.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_quadTR_11to50.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_lt51bp_gt95identity_merged.bed.gz | /Applications/bioinfo/bedtools2/bin/complementBed -i stdin -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/tabix/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/AllRepeats_lt51bp_gt95identity_merged.bed.gz

/Applications/bioinfo/bedtools2/bin/complementBed -i /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_51to200bp_gt95identity_merged.bed.gz -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_diTR_51to200.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_triTR_51to200.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_quadTR_51to200.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_51to200bp_gt95identity_merged.bed.gz | /Applications/bioinfo/bedtools2/bin/complementBed -i stdin -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/AllRepeats_51to200bp_gt95identity_merged.bed.gz

/Applications/bioinfo/bedtools2/bin/complementBed -i /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_gt200bp_gt95identity_merged.bed.gz -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_diTR_gt200.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_triTR_gt200.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_quadTR_gt200.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_gt200bp_gt95identity_merged.bed.gz | /Applications/bioinfo/bedtools2/bin/complementBed -i stdin -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/tabix-0.2.6/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/AllRepeats_gt200bp_gt95identity_merged.bed.gz

/Applications/bioinfo/bedtools2/bin/slopBed -i /Applications/bioinfo/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllRepeats_lt51bp_gt95identity_merged.bed.gz -b 5 -g /Applications/bioinfo/nist-integration-v3.1/resources/human.b37.genome | /Applications/bioinfo/tabix/bgzip -c > /Applications/bioinfo/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllRepeats_lt51bp_gt95identity_merged_slop5.bed.gz
/Applications/bioinfo/bedtools2/bin/slopBed -i /Applications/bioinfo/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllRepeats_51to200bp_gt95identity_merged.bed.gz -b 5 -g /Applications/bioinfo/nist-integration-v3.1/resources/human.b37.genome | /Applications/bioinfo/tabix/bgzip -c > /Applications/bioinfo/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllRepeats_51to200bp_gt95identity_merged_slop5.bed.gz
/Applications/bioinfo/bedtools2/bin/slopBed -i /Applications/bioinfo/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllRepeats_gt200bp_gt95identity_merged.bed.gz -b 5 -g /Applications/bioinfo/nist-integration-v3.1/resources/human.b37.genome | /Applications/bioinfo/tabix/bgzip -c > /Applications/bioinfo/benchmarking-tools/resources/stratification-bed-files/LowComplexity/AllRepeats_gt200bp_gt95identity_merged_slop5.bed.gz

/Applications/bioinfo/bedtools2/bin/complementBed -i /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_lt51bp_gt95identity_merged.bed.gz -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_diTR_11to50.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_triTR_11to50.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/SimpleRepeat_quadTR_11to50.bed.gz | /Applications/bioinfo/bedtools2/bin/subtractBed -a stdin -b /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_lt51bp_gt95identity_merged.bed.gz | /Applications/bioinfo/bedtools2/bin/complementBed -i stdin -g /Applications/bioinfo/bedtools2/genomes/human.b37.genome | /Applications/bioinfo/tabix/bgzip > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/AllRepeats_lt51bptandemrepeats_gt95identity_merged.bed.gz
/Applications/bioinfo/bedtools2/bin/slopBed -i /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/AllRepeats_lt51bptandemrepeats_gt95identity_merged.bed.gz -b 5 -g /Applications/bioinfo/nist-integration-v3.1/resources/human.b37.genome | /Applications/bioinfo/tabix/bgzip -c > /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/AllRepeats_lt51bptandemrepeats_gt95identity_merged_slop5.bed.gz

#Make bed with all repeats and its complement
/Applications/bioinfo/bedtools2/bin/multiIntersectBed -i /Users/jzook/Downloads/work/bed_files/LowComplexity/AllRepeats_gt200bp_gt95identity_merged_slop5.bed.gz /Users/jzook/Downloads/work/bed_files/LowComplexity/AllRepeats_51to200bp_gt95identity_merged_slop5.bed.gz /Users/jzook/Downloads/work/bed_files/LowComplexity/AllRepeats_lt51bp_gt95identity_merged_slop5.bed.gz | /Applications/bioinfo/bedtools2/bin/mergeBed -i stdin | /Applications/bioinfo/tabix/bgzip -c > /Users/jzook/Downloads/work/bed_files/LowComplexity/AllRepeats_gt95percidentity_slop5.bed.gz

/Applications/bioinfo/bedtools2/bin/subtractBed -a /Applications/bioinfo/nist-integration-v3.1/resources/human.b37.genome.bed -b /Users/jzook/Downloads/work/bed_files/LowComplexity/AllRepeats_gt95percidentity_slop5.bed.gz | /Applications/bioinfo/tabix/bgzip -c > /Users/jzook/Downloads/work/bed_files/LowComplexity/notinAllRepeats_gt95percidentity_slop5.bed.gz


#awk '{sum+=$3;sum-=$2} END {print sum}'  /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_all_merged.bed
#71143602
#awk '{sum+=$3;sum-=$2} END {print sum}'  /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_all_gt95identity_merged.bed
#23789309
#awk '{sum+=$3;sum-=$2} END {print sum}'  /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_gt100bp_gt95identity_merged.bed
#140076
#awk '{sum+=$3;sum-=$2} END {print sum}'  /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRlt7_lt101bp_gt95identity_merged.bed
#7181114
#awk '{sum+=$3;sum-=$2} END {print sum}'  /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_gt100bp_gt95identity_merged.bed
#8568047
#awk '{sum+=$3;sum-=$2} END {print sum}'  /Users/jzook/Documents/GA4GH/StratificationBedFiles/LowComplexity/Human_Full_Genome_TRDB_hg19_150331_TRgt6_lt101bp_gt95identity_merged.bed
#8167453



